version: "2"
services:
  hackathon:
    container_name: hackathon-node
    build: .
    ports:
      - "8080:8080"
    links:
      - mongo
  mongo:
    container_name: hackathon-mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
